// Code generated by MockGen. DO NOT EDIT.
// Source: test-system/internal/domain/calculation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock_calc_test.go -package=query -mock_names Repository=MockCalculationRepository test-system/internal/domain/calculation Repository
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"
	calculation "test-system/internal/domain/calculation"

	gomock "go.uber.org/mock/gomock"
)

// MockCalculationRepository is a mock of Repository interface.
type MockCalculationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCalculationRepositoryMockRecorder
	isgomock struct{}
}

// MockCalculationRepositoryMockRecorder is the mock recorder for MockCalculationRepository.
type MockCalculationRepositoryMockRecorder struct {
	mock *MockCalculationRepository
}

// NewMockCalculationRepository creates a new mock instance.
func NewMockCalculationRepository(ctrl *gomock.Controller) *MockCalculationRepository {
	mock := &MockCalculationRepository{ctrl: ctrl}
	mock.recorder = &MockCalculationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculationRepository) EXPECT() *MockCalculationRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCalculationRepository) GetByID(ctx context.Context, id string) (*calculation.Calculation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*calculation.Calculation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCalculationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCalculationRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockCalculationRepository) Save(ctx context.Context, arg1 *calculation.Calculation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCalculationRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCalculationRepository)(nil).Save), ctx, arg1)
}

// Search mocks base method.
func (m *MockCalculationRepository) Search(ctx context.Context, search calculation.Search) ([]calculation.Calculation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, search)
	ret0, _ := ret[0].([]calculation.Calculation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCalculationRepositoryMockRecorder) Search(ctx, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCalculationRepository)(nil).Search), ctx, search)
}
